export interface Professional {
  id: string
  name: string
  category: string
  rating: number
  reviewCount: number
  experience: number
  hourlyRate: number
  location: string
  bio: string
  skills: string[]
  availability: string
  verified: boolean
  completedJobs: number
  image: string
}

export const professionals: Professional[] = [
  {
    id: "1",
    name: "Carlos Mendoza",
    category: "Plomería",
    rating: 4.9,
    reviewCount: 127,
    experience: 8,
    hourlyRate: 35,
    location: "Ciudad de México, CDMX",
    bio: "Plomero certificado con más de 8 años de experiencia. Especializado en reparaciones de emergencia, instalaciones de baños y cocinas, y mantenimiento preventivo.",
    skills: ["Reparación de fugas", "Instalación de tuberías", "Destapado de drenajes", "Calentadores de agua"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 342,
    image: "/professional-plumber-headshot.jpg",
  },
  {
    id: "2",
    name: "Ana Rodríguez",
    category: "Electricidad",
    rating: 5.0,
    reviewCount: 98,
    experience: 6,
    hourlyRate: 40,
    location: "Guadalajara, JAL",
    bio: "Electricista certificada con especialización en instalaciones residenciales y comerciales. Experta en sistemas de iluminación LED y paneles solares.",
    skills: ["Instalaciones eléctricas", "Iluminación LED", "Paneles solares", "Reparación de cortocircuitos"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 256,
    image: "/professional-electrician-headshot.jpg",
  },
  {
    id: "3",
    name: "Roberto Sánchez",
    category: "Carpintería",
    rating: 4.8,
    reviewCount: 156,
    experience: 12,
    hourlyRate: 38,
    location: "Monterrey, NL",
    bio: "Carpintero maestro con más de una década de experiencia. Especializado en muebles a medida, remodelaciones y restauración de madera.",
    skills: ["Muebles a medida", "Remodelación", "Restauración", "Instalación de pisos"],
    availability: "Disponible en 2 días",
    verified: true,
    completedJobs: 428,
    image: "/professional-carpenter-headshot.jpg",
  },
  {
    id: "4",
    name: "María González",
    category: "Pintura",
    rating: 4.9,
    reviewCount: 89,
    experience: 5,
    hourlyRate: 30,
    location: "Puebla, PUE",
    bio: "Pintora profesional con ojo para el detalle. Especializada en acabados decorativos, pintura de interiores y exteriores con garantía de calidad.",
    skills: ["Pintura interior", "Pintura exterior", "Acabados decorativos", "Texturizados"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 198,
    image: "/professional-painter-headshot.jpg",
  },
  {
    id: "5",
    name: "Luis Hernández",
    category: "Limpieza",
    rating: 4.7,
    reviewCount: 203,
    experience: 4,
    hourlyRate: 25,
    location: "Ciudad de México, CDMX",
    bio: "Especialista en limpieza profunda residencial y comercial. Uso de productos ecológicos y técnicas profesionales para resultados impecables.",
    skills: ["Limpieza profunda", "Limpieza post-construcción", "Productos ecológicos", "Desinfección"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 567,
    image: "/professional-cleaner-headshot.jpg",
  },
  {
    id: "6",
    name: "Jorge Ramírez",
    category: "Seguridad",
    rating: 5.0,
    reviewCount: 74,
    experience: 10,
    hourlyRate: 45,
    location: "Querétaro, QRO",
    bio: "Cerrajero y especialista en seguridad con certificaciones internacionales. Experto en cerraduras de alta seguridad y sistemas de control de acceso.",
    skills: ["Cerrajería", "Sistemas de seguridad", "Control de acceso", "Cámaras de vigilancia"],
    availability: "Disponible en 24h",
    verified: true,
    completedJobs: 312,
    image: "/professional-security-headshot.jpg",
  },
  {
    id: "7",
    name: "Patricia Morales",
    category: "Jardinería",
    rating: 4.8,
    reviewCount: 112,
    experience: 7,
    hourlyRate: 32,
    location: "Guadalajara, JAL",
    bio: "Paisajista y jardinera profesional. Especializada en diseño de jardines, mantenimiento y sistemas de riego automatizado.",
    skills: ["Diseño de jardines", "Mantenimiento", "Sistemas de riego", "Poda especializada"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 289,
    image: "/professional-gardener-headshot.jpg",
  },
  {
    id: "8",
    name: "Miguel Torres",
    category: "Mecánica",
    rating: 4.9,
    reviewCount: 145,
    experience: 15,
    hourlyRate: 50,
    location: "Monterrey, NL",
    bio: "Mecánico automotriz certificado con 15 años de experiencia. Especializado en diagnóstico computarizado y reparaciones de motor.",
    skills: ["Diagnóstico computarizado", "Reparación de motor", "Transmisión", "Mantenimiento preventivo"],
    availability: "Disponible en 3 días",
    verified: true,
    completedJobs: 521,
    image: "/professional-mechanic-headshot.jpg",
  },
  {
    id: "9",
    name: "Sandra López",
    category: "Plomería",
    rating: 4.8,
    reviewCount: 91,
    experience: 5,
    hourlyRate: 33,
    location: "Puebla, PUE",
    bio: "Plomera profesional especializada en instalaciones modernas y reparaciones de emergencia. Atención rápida y trabajo garantizado.",
    skills: ["Instalaciones sanitarias", "Reparación de fugas", "Sistemas de agua caliente", "Mantenimiento"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 234,
    image: "/professional-plumber2-headshot.jpg",
  },
  {
    id: "10",
    name: "Fernando Díaz",
    category: "Electricidad",
    rating: 4.7,
    reviewCount: 68,
    experience: 9,
    hourlyRate: 42,
    location: "Ciudad de México, CDMX",
    bio: "Electricista industrial y residencial. Experto en instalaciones de alta y baja tensión, automatización del hogar y eficiencia energética.",
    skills: ["Automatización del hogar", "Instalaciones industriales", "Eficiencia energética", "Tableros eléctricos"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 287,
    image: "/professional-electrician2-headshot.jpg",
  },
  {
    id: "11",
    name: "Elena Vargas",
    category: "Limpieza",
    rating: 5.0,
    reviewCount: 134,
    experience: 6,
    hourlyRate: 28,
    location: "Querétaro, QRO",
    bio: "Especialista en limpieza residencial con enfoque en atención al detalle. Servicios personalizados y uso de productos de alta calidad.",
    skills: ["Limpieza residencial", "Organización", "Limpieza de alfombras", "Cristales"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 445,
    image: "/professional-cleaner2-headshot.jpg",
  },
  {
    id: "12",
    name: "Ricardo Flores",
    category: "Carpintería",
    rating: 4.9,
    reviewCount: 102,
    experience: 11,
    hourlyRate: 40,
    location: "Guadalajara, JAL",
    bio: "Carpintero especializado en cocinas integrales y closets a medida. Diseños modernos con materiales de primera calidad.",
    skills: ["Cocinas integrales", "Closets", "Muebles de baño", "Diseño 3D"],
    availability: "Disponible en 4 días",
    verified: true,
    completedJobs: 356,
    image: "/professional-carpenter2-headshot.jpg",
  },
]

export const categories = [
  "Todos",
  "Plomería",
  "Electricidad",
  "Carpintería",
  "Pintura",
  "Limpieza",
  "Seguridad",
  "Jardinería",
  "Mecánica",
]

export const cities = ["Todas", "Ciudad de México", "Guadalajara", "Monterrey", "Puebla", "Querétaro"]
