export interface Professional {
  id: string
  name: string
  category: string
  rating: number
  reviewCount: number
  experience: number
  hourlyRate: number
  location: string
  bio: string
  skills: string[]
  availability: string
  verified: boolean
  completedJobs: number
  image: string
}

export const professionals: Professional[] = [
  {
    id: "1",
    name: "Carlos Mendoza",
    category: "Plomería",
    rating: 4.9,
    reviewCount: 127,
    experience: 8,
    hourlyRate: 35,
    location: "Buenos Aires, Argentina",
    bio: "Plomero certificado con más de 8 años de experiencia. Especializado en reparaciones de emergencia, instalaciones de baños y cocinas, y mantenimiento preventivo.",
    skills: ["Reparación de fugas", "Instalación de tuberías", "Destapado de drenajes", "Calentadores de agua"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 342,
    image: "/professional-plumber-headshot.jpg",
  },
  {
    id: "2",
    name: "Ana Rodríguez",
    category: "Electricidad",
    rating: 5.0,
    reviewCount: 98,
    experience: 6,
    hourlyRate: 40,
    location: "Córdoba, Argentina",
    bio: "Electricista certificada con especialización en instalaciones residenciales y comerciales. Experta en sistemas de iluminación LED y paneles solares.",
    skills: ["Instalaciones eléctricas", "Iluminación LED", "Paneles solares", "Reparación de cortocircuitos"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 256,
    image: "/professional-electrician-headshot.jpg",
  },
  {
    id: "3",
    name: "Roberto Sánchez",
    category: "Carpintería",
    rating: 4.8,
    reviewCount: 156,
    experience: 12,
    hourlyRate: 38,
    location: "Rosario, Argentina",
    bio: "Carpintero maestro con más de una década de experiencia. Especializado en muebles a medida, remodelaciones y restauración de madera.",
    skills: ["Muebles a medida", "Remodelación", "Restauración", "Instalación de pisos"],
    availability: "Disponible en 2 días",
    verified: true,
    completedJobs: 428,
    image: "/professional-carpenter-headshot.jpg",
  },
  {
    id: "4",
    name: "María González",
    category: "Pintura",
    rating: 4.9,
    reviewCount: 89,
    experience: 5,
    hourlyRate: 30,
    location: "Mendoza, Argentina",
    bio: "Pintora profesional con ojo para el detalle. Especializada en acabados decorativos, pintura de interiores y exteriores con garantía de calidad.",
    skills: ["Pintura interior", "Pintura exterior", "Acabados decorativos", "Texturizados"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 198,
    image: "/professional-painter-headshot.jpg",
  },
  {
    id: "5",
    name: "Luis Hernández",
    category: "Limpieza",
    rating: 4.7,
    reviewCount: 203,
    experience: 4,
    hourlyRate: 25,
    location: "La Plata, Argentina",
    bio: "Especialista en limpieza profunda residencial y comercial. Uso de productos ecológicos y técnicas profesionales para resultados impecables.",
    skills: ["Limpieza profunda", "Limpieza post-construcción", "Productos ecológicos", "Desinfección"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 567,
    image: "/professional-cleaner-headshot.jpg",
  },
  {
    id: "6",
    name: "Jorge Ramírez",
    category: "Seguridad",
    rating: 5.0,
    reviewCount: 74,
    experience: 10,
    hourlyRate: 45,
    location: "Mar del Plata, Argentina",
    bio: "Cerrajero y especialista en seguridad con certificaciones internacionales. Experto en cerraduras de alta seguridad y sistemas de control de acceso.",
    skills: ["Cerrajería", "Sistemas de seguridad", "Control de acceso", "Cámaras de vigilancia"],
    availability: "Disponible en 24h",
    verified: true,
    completedJobs: 312,
    image: "/professional-security-headshot.jpg",
  },
  {
    id: "7",
    name: "Patricia Morales",
    category: "Jardinería",
    rating: 4.8,
    reviewCount: 112,
    experience: 7,
    hourlyRate: 32,
    location: "Salta, Argentina",
    bio: "Paisajista y jardinera profesional. Especializada en diseño de jardines, mantenimiento y sistemas de riego automatizado.",
    skills: ["Diseño de jardines", "Mantenimiento", "Sistemas de riego", "Poda especializada"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 289,
    image: "/professional-gardener-headshot.jpg",
  },
  {
    id: "8",
    name: "Miguel Torres",
    category: "Mecánica",
    rating: 4.9,
    reviewCount: 145,
    experience: 15,
    hourlyRate: 50,
    location: "Tucumán, Argentina",
    bio: "Mecánico automotriz certificado con 15 años de experiencia. Especializado en diagnóstico computarizado y reparaciones de motor.",
    skills: ["Diagnóstico computarizado", "Reparación de motor", "Transmisión", "Mantenimiento preventivo"],
    availability: "Disponible en 3 días",
    verified: true,
    completedJobs: 521,
    image: "/professional-mechanic-headshot.jpg",
  },
  {
    id: "9",
    name: "Sandra López",
    category: "Plomería",
    rating: 4.8,
    reviewCount: 91,
    experience: 5,
    hourlyRate: 33,
    location: "Buenos Aires, Argentina",
    bio: "Plomera profesional especializada en instalaciones modernas y reparaciones de emergencia. Atención rápida y trabajo garantizado.",
    skills: ["Instalaciones sanitarias", "Reparación de fugas", "Sistemas de agua caliente", "Mantenimiento"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 234,
    image: "/professional-plumber2-headshot.jpg",
  },
  {
    id: "10",
    name: "Fernando Díaz",
    category: "Electricidad",
    rating: 4.7,
    reviewCount: 68,
    experience: 9,
    hourlyRate: 42,
    location: "Córdoba, Argentina",
    bio: "Electricista industrial y residencial. Experto en instalaciones de alta y baja tensión, automatización del hogar y eficiencia energética.",
    skills: ["Automatización del hogar", "Instalaciones industriales", "Eficiencia energética", "Tableros eléctricos"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 287,
    image: "/professional-electrician2-headshot.jpg",
  },
  {
    id: "11",
    name: "Elena Vargas",
    category: "Limpieza",
    rating: 5.0,
    reviewCount: 134,
    experience: 6,
    hourlyRate: 28,
    location: "Rosario, Argentina",
    bio: "Especialista en limpieza residencial con enfoque en atención al detalle. Servicios personalizados y uso de productos de alta calidad.",
    skills: ["Limpieza residencial", "Organización", "Limpieza de alfombras", "Cristales"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 445,
    image: "/professional-cleaner2-headshot.jpg",
  },
  {
    id: "12",
    name: "Ricardo Flores",
    category: "Carpintería",
    rating: 4.9,
    reviewCount: 102,
    experience: 11,
    hourlyRate: 40,
    location: "Mendoza, Argentina",
    bio: "Carpintero especializado en cocinas integrales y closets a medida. Diseños modernos con materiales de primera calidad.",
    skills: ["Cocinas integrales", "Closets", "Muebles de baño", "Diseño 3D"],
    availability: "Disponible en 4 días",
    verified: true,
    completedJobs: 356,
    image: "/professional-carpenter2-headshot.jpg",
  },
  {
    id: "13",
    name: "Gabriela Martínez",
    category: "Pintura",
    rating: 4.8,
    reviewCount: 76,
    experience: 7,
    hourlyRate: 32,
    location: "La Plata, Argentina",
    bio: "Pintora especializada en técnicas decorativas y restauración. Trabajos de alta calidad con atención al detalle y acabados perfectos.",
    skills: ["Pintura decorativa", "Restauración", "Murales", "Estuco veneciano"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 267,
    image: "/professional-painter-headshot.jpg",
  },
  {
    id: "14",
    name: "Martín Acosta",
    category: "Plomería",
    rating: 4.9,
    reviewCount: 143,
    experience: 10,
    hourlyRate: 37,
    location: "Mar del Plata, Argentina",
    bio: "Plomero con amplia experiencia en instalaciones comerciales y residenciales. Servicio de emergencia 24/7 disponible.",
    skills: ["Instalaciones comerciales", "Gas natural", "Sistemas de calefacción", "Emergencias 24/7"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 489,
    image: "/professional-plumber-headshot.jpg",
  },
  {
    id: "15",
    name: "Lucía Fernández",
    category: "Electricidad",
    rating: 5.0,
    reviewCount: 112,
    experience: 8,
    hourlyRate: 43,
    location: "Salta, Argentina",
    bio: "Electricista especializada en domótica y sistemas inteligentes. Certificada en instalaciones de energía renovable.",
    skills: ["Domótica", "Smart home", "Energía solar", "Automatización"],
    availability: "Disponible en 2 días",
    verified: true,
    completedJobs: 334,
    image: "/professional-electrician-headshot.jpg",
  },
  {
    id: "16",
    name: "Diego Romero",
    category: "Carpintería",
    rating: 4.7,
    reviewCount: 88,
    experience: 9,
    hourlyRate: 36,
    location: "Tucumán, Argentina",
    bio: "Carpintero artesanal especializado en muebles rústicos y contemporáneos. Trabajos personalizados con maderas nobles.",
    skills: ["Muebles rústicos", "Diseño personalizado", "Maderas nobles", "Acabados finos"],
    availability: "Disponible en 5 días",
    verified: true,
    completedJobs: 298,
    image: "/professional-carpenter-headshot.jpg",
  },
  {
    id: "17",
    name: "Valeria Castro",
    category: "Limpieza",
    rating: 4.9,
    reviewCount: 167,
    experience: 5,
    hourlyRate: 27,
    location: "Buenos Aires, Argentina",
    bio: "Especialista en limpieza de oficinas y espacios comerciales. Equipos profesionales y productos certificados.",
    skills: ["Limpieza comercial", "Oficinas", "Desinfección profesional", "Mantenimiento"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 623,
    image: "/professional-cleaner-headshot.jpg",
  },
  {
    id: "18",
    name: "Sebastián Ruiz",
    category: "Seguridad",
    rating: 4.8,
    reviewCount: 95,
    experience: 12,
    hourlyRate: 48,
    location: "Córdoba, Argentina",
    bio: "Experto en seguridad electrónica y sistemas de alarma. Instalación y mantenimiento de equipos de última generación.",
    skills: ["Alarmas", "CCTV", "Seguridad electrónica", "Monitoreo remoto"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 401,
    image: "/professional-security-headshot.jpg",
  },
  {
    id: "19",
    name: "Carolina Benítez",
    category: "Jardinería",
    rating: 5.0,
    reviewCount: 129,
    experience: 8,
    hourlyRate: 34,
    location: "Rosario, Argentina",
    bio: "Paisajista con especialización en jardines sustentables. Diseño, implementación y mantenimiento de espacios verdes.",
    skills: ["Jardines sustentables", "Huertos urbanos", "Paisajismo", "Riego inteligente"],
    availability: "Disponible en 3 días",
    verified: true,
    completedJobs: 356,
    image: "/professional-gardener-headshot.jpg",
  },
  {
    id: "20",
    name: "Andrés Peralta",
    category: "Mecánica",
    rating: 4.8,
    reviewCount: 178,
    experience: 13,
    hourlyRate: 52,
    location: "Mendoza, Argentina",
    bio: "Mecánico especializado en vehículos europeos y asiáticos. Diagnóstico avanzado y reparaciones complejas.",
    skills: ["Vehículos europeos", "Inyección electrónica", "Frenos ABS", "Aire acondicionado"],
    availability: "Disponible en 2 días",
    verified: true,
    completedJobs: 587,
    image: "/professional-mechanic-headshot.jpg",
  },
  {
    id: "21",
    name: "Natalia Vega",
    category: "Pintura",
    rating: 4.9,
    reviewCount: 104,
    experience: 6,
    hourlyRate: 31,
    location: "La Plata, Argentina",
    bio: "Pintora especializada en técnicas modernas y acabados premium. Trabajos residenciales y comerciales de alta gama.",
    skills: ["Acabados premium", "Microcemento", "Pintura a la tiza", "Efectos especiales"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 312,
    image: "/professional-painter-headshot.jpg",
  },
  {
    id: "22",
    name: "Pablo Gutiérrez",
    category: "Electricidad",
    rating: 4.7,
    reviewCount: 81,
    experience: 11,
    hourlyRate: 41,
    location: "Mar del Plata, Argentina",
    bio: "Electricista matriculado con experiencia en proyectos industriales. Instalaciones de media y baja tensión.",
    skills: ["Proyectos industriales", "Media tensión", "Tableros de comando", "Puesta a tierra"],
    availability: "Disponible mañana",
    verified: true,
    completedJobs: 378,
    image: "/professional-electrician2-headshot.jpg",
  },
  {
    id: "23",
    name: "Florencia Ibarra",
    category: "Limpieza",
    rating: 5.0,
    reviewCount: 192,
    experience: 7,
    hourlyRate: 29,
    location: "Salta, Argentina",
    bio: "Especialista en limpieza post-obra y mudanzas. Equipo profesional y resultados garantizados en tiempo récord.",
    skills: ["Post-obra", "Mudanzas", "Limpieza express", "Pulido de pisos"],
    availability: "Disponible hoy",
    verified: true,
    completedJobs: 701,
    image: "/professional-cleaner2-headshot.jpg",
  },
  {
    id: "24",
    name: "Maximiliano Silva",
    category: "Carpintería",
    rating: 4.9,
    reviewCount: 118,
    experience: 14,
    hourlyRate: 42,
    location: "Tucumán, Argentina",
    bio: "Maestro carpintero especializado en obras arquitectónicas y estructuras de madera. Proyectos a medida de gran envergadura.",
    skills: ["Estructuras de madera", "Pérgolas", "Decks", "Proyectos arquitectónicos"],
    availability: "Disponible en 7 días",
    verified: true,
    completedJobs: 467,
    image: "/professional-carpenter2-headshot.jpg",
  },
]

export const categories = [
  "Todos",
  "Plomería",
  "Electricidad",
  "Carpintería",
  "Pintura",
  "Limpieza",
  "Seguridad",
  "Jardinería",
  "Mecánica",
]

export const cities = [
  "Todas",
  "Buenos Aires",
  "Córdoba",
  "Rosario",
  "Mendoza",
  "La Plata",
  "Mar del Plata",
  "Salta",
  "Tucumán",
]
